openapi: 3.0.0
info:
  title: Plan Management API
  version: 1.0.0
  description: 주간 계획표 관리 서비스의 API 문서입니다.
servers:
  - url: http://localhost:4000/api
    description: Local server

paths:
  /auth/signup:
    post:
      summary: "회원가입"
      description: "새로운 사용자를 등록합니다. (관리자 권한 필요)"
      tags: [Auth]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: string
                  example: "test_user"
                password:
                  type: string
                  example: "123456"
                user_name:
                  type: string
                  example: "홍길동"
                number:
                  type: string
                  example: "01012345678"
                role:
                  type: string
                  example: "사원"
      responses:
        "201":
          description: "회원가입 성공"
        "400":
          description: "입력값 오류 또는 중복 ID"
        "500":
          description: "서버 오류"

  /auth/login:
    post:
      summary: "로그인"
      description: "아이디와 비밀번호로 로그인 후 토큰 발급."
      tags: [Auth]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: string
                password:
                  type: string
      responses:
        "200":
          description: "로그인 성공 (accessToken 및 isAdmin 반환)"
        "400":
          description: "아이디 또는 비밀번호 오류"
        "500":
          description: "서버 오류"

  /auth:
    get:
      summary: "로그인 상태 확인"
      tags: [Auth]
      responses:
        "200":
          description: "로그인됨"
        "401":
          description: "로그인되지 않음"
        "500":
          description: "서버 오류"

  /auth/refresh:
    post:
      summary: "Access Token 갱신"
      tags: [Auth]
      responses:
        "200":
          description: "토큰 재발급 성공"
        "403":
          description: "Refresh Token 오류"

  /auth/logout:
    post:
      summary: "로그아웃"
      tags: [Auth]
      responses:
        "200":
          description: "로그아웃 성공"
        "500":
          description: "서버 오류"

  /auth:
    delete:
      summary: "유저 삭제"
      description: "이름으로 유저를 삭제합니다. (관리자 전용)"
      tags: [Auth]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_name:
                  type: string
      responses:
        "200":
          description: "삭제 성공"
        "400":
          description: "입력 누락"
        "404":
          description: "유저 없음"
        "500":
          description: "서버 오류"

  /auth/update:
    patch:
      summary: "유저 정보 수정"
      description: "현재 로그인한 사용자의 정보를 수정합니다."
      tags: [Auth]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_name:
                  type: string
                  example: "김유진"
                number:
                  type: string
                  example: "01012345678"
                role:
                  type: string
                  example: "사원"
      responses:
        "200":
          description: "수정 성공"
        "400":
          description: "잘못된 요청 또는 수정할 정보 없음"
        "404":
          description: "사용자 없음"
        "500":
          description: "서버 오류"


  /auth/password:
    patch:
      summary: "비밀번호 변경"
      description: "현재 로그인한 사용자가 비밀번호를 변경합니다."
      tags: [Auth]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                currentPassword:
                  type: string
                  example: "123456"
                newPassword:
                  type: string
                  example: "newpassword123"
      responses:
        "200":
          description: "비밀번호 변경 성공"
        "400":
          description: "입력 누락 또는 형식 오류"
        "401":
          description: "현재 비밀번호가 일치하지 않음"
        "404":
          description: "사용자 없음"
        "500":
          description: "서버 오류"


  /folders:
    get:
      summary: "폴더 목록 조회"
      tags: [Folders]
      responses:
        "200":
          description: "폴더 목록 조회 성공"
        "500":
          description: "서버 오류"
    post:
      summary: "폴더 추가"
      tags: [Folders]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                folder_name:
                  type: string
                  example: "업무폴더"
      responses:
        "201":
          description: "폴더 추가 성공"
        "400":
          description: "잘못된 요청"
        "500":
          description: "서버 오류"

  /folders/{fid}:
    put:
      summary: "폴더 이름 수정"
      tags: [Folders]
      parameters:
        - in: path
          name: fid
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                folder_name:
                  type: string
                  example: "새 폴더명"
      responses:
        "200":
          description: "폴더 수정 완료"
        "500":
          description: "서버 오류"
    delete:
      summary: "폴더 삭제"
      tags: [Folders]
      parameters:
        - in: path
          name: fid
          required: true
          schema:
            type: integer
      responses:
        "204":
          description: "폴더 삭제 완료"
        "404":
          description: "폴더를 찾을 수 없음"
        "500":
          description: "서버 오류"

  /folders/{fid}/plans:
    get:
      summary: "계획표 목록 조회"
      tags: [Plans]
      parameters:
        - in: path
          name: fid
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: "계획표 목록 조회 성공"
        "500":
          description: "서버 오류"
    post:
      summary: "계획표 추가"
      tags: [Plans]
      parameters:
        - in: path
          name: fid
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                week:
                  type: string
                table:
                  type: array
                  items:
                    type: array
                    items:
                      type: string
      responses:
        "201":
          description: "계획표 추가 완료"
        "500":
          description: "서버 오류"

  /folders/{fid}/plans/{pid}:
    put:
      summary: "계획표 수정"
      tags: [Plans]
      parameters:
        - in: path
          name: fid
          required: true
          schema:
            type: integer
        - in: path
          name: pid
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                week:
                  type: string
                table:
                  type: array
                  items:
                    type: array
                    items:
                      type: string
      responses:
        "200":
          description: "계획표 수정 완료"
        "404":
          description: "해당 계획표 없음"
        "500":
          description: "서버 오류"
    delete:
      summary: "계획표 삭제"
      tags: [Plans]
      parameters:
        - in: path
          name: fid
          required: true
          schema:
            type: integer
        - in: path
          name: pid
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: "계획표 삭제 완료"
        "404":
          description: "계획표를 찾을 수 없음"
        "500":
          description: "서버 오류"

  /folders/{fid}/plans/{pid}/projects:
    get:
      summary: "계획표의 프로젝트 및 유저 정보 조회"
      tags: [Plans]
      parameters:
        - in: path
          name: fid
          required: true
          schema:
            type: integer
        - in: path
          name: pid
          required: true
          schema:
            type: string
      responses:
        "200":
          description: "프로젝트 및 유저 정보 조회 성공"
        "500":
          description: "서버 오류"

  /folders/{fid}/plans/{pid}/feedback:
    put:
      summary: "피드백 수정"
      tags: [Plans]
      parameters:
        - in: path
          name: fid
          required: true
          schema:
            type: integer
        - in: path
          name: pid
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                feedback:
                  type: string
      responses:
        "200":
          description: "Feedback 수정 완료"
        "500":
          description: "서버 오류"

  /search:
    get:
      summary: "키워드로 사용자 데이터 검색"
      description: |
        현재 사용자가 소유한 폴더, 계획표, 프로젝트를 키워드로 검색합니다.
        프로젝트는 project_name, last_week, this_week 필드도 검색에 포함됩니다.
      tags: [Search]
      parameters:
        - in: query
          name: keyword
          schema:
            type: string
          required: true
          description: "검색어"
      responses:
        "200":
          description: "검색 결과 반환 성공"
          content:
            application/json:
              schema:
                type: object
                properties:
                  folders:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        folder_name:
                          type: string
                  plans:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        title:
                          type: string
                        fid:
                          type: integer
                  projects:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        project_name:
                          type: string
                        last_week:
                          type: string
                        this_week:
                          type: string
                        pid:
                          type: integer
                        fid:
                          type: integer
        "400":
          description: "검색어 누락"
        "500":
          description: "서버 오류"


  /history/undo:
    post:
      summary: "마지막 작업 되돌리기 (Undo)"
      tags: [History]
      responses:
        "200":
          description: "Undo 성공"
        "500":
          description: "서버 오류"

  /history/redo:
    post:
      summary: "되돌리기 작업 다시 실행 (Redo)"
      tags: [History]
      responses:
        "200":
          description: "Redo 성공"
        "500":
          description: "서버 오류"

tags:
  - name: Auth
    description: 사용자 인증 관련 API
  - name: Folders
    description: 폴더 관리 API
  - name: History
    description: Undo/Redo 이력 관리 API
